name: Setup Tailscale 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Проверка каждые 6 часов

jobs:
  tailscale-vpn:
    runs-on: self-hosted
    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Authenticate Tailscale (только при первом запуске)
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          if ! sudo tailscale status 2>/dev/null | grep -q "Logged in"; then
            echo "Первоначальная настройка Tailscale..."
            sudo tailscale up --authkey="$TAILSCALE_AUTH_KEY" --accept-routes --accept-dns --reset
          else
            echo "Tailscale уже настроен, пропускаем аутентификацию"
          fi

      - name: Ensure Tailscale is running
        run: |
          sudo tailscale up --accept-routes --accept-dns

      - name: Enable IP forwarding
        run: |
          echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.conf
          echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.conf
          sudo sysctl -p

      - name: Verify connection
        run: |
          echo "Tailscale Status:"
          sudo tailscale status
          echo "Tailscale IP:"
          sudo tailscale ip -4

      - name: Ensure Tailscale auto-start
        run: |
          sudo systemctl enable tailscaled
          sudo systemctl start tailscaled

      - name: Create persistent service (на всякий случай)
        run: |
          sudo tee /etc/systemd/system/tailscale-persistent.service > /dev/null <<EOF
[Unit]
Description=Tailscale Persistent VPN
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/tailscale up --accept-routes --accept-dns
Restart=always
RestartSec=10
User=root

[Install]
WantedBy=multi-user.target
EOF
          sudo systemctl daemon-reload
          sudo systemctl enable tailscale-persistent.service
